version: '3.8'

services:
  mongodb:
    image: mongo:latest
    networks:
      - my-network

  mon-app:
    build: .
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - mongodb

networks:
  my-network:
    driver: bridge
